image:
  file: .gitpod.dockerfile

ports:
- port: 3000
- port: 8080
- port: 5000-5999
  onOpen: ignore

tasks:
- init: |
    cd /workspace/extension-registry/webui
    yarn
    yarn build:dev
    cd /workspace/extension-registry/server
    ./gradlew build -x buildNative -x testNative
  command: |
    cd /workspace/extension-registry/webui
    yarn run:dev
